### ISSUE TITLE
Create a cluster after deleting the cluster, port 10259 is in use

### ISSUE THREAD

**Issue by Mengchenchen** [kubeclipper/kubeclipper#112]
**Describe the Bug**
Create a cluster after deleting the cluster, port 10259 is in use

![in use](https://user-images.githubusercontent.com/100403985/184589126-2dc13b2e-92e9-4545-982a-acee1f9c61a3.png)

<img width="968" alt="port" src="https://user-images.githubusercontent.com/100403985/184589138-08bfc1d5-f52d-4886-bd9b-b44d92f50fd8.png">

**Comment by lixd** [comment]
fixed by #227
