### ISSUE TITLE
The regions that use the cluster template to create clusters are always default

### ISSUE THREAD

**Issue by Mengchenchen** [kubeclipper/kubeclipper#115]
**Describe the Bug**
The regions that use the cluster template to create clusters are always default

But the node does not belong to default area

![区域](https://user-images.githubusercontent.com/100403985/184612383-16a962ec-efa4-4c7b-a47b-311477ed35d8.png)

![节点](https://user-images.githubusercontent.com/100403985/184612403-ac48414f-62cc-4ed1-83d0-011711de5cb6.png)

**Comment by x893675** [comment]
/area console
@moweiwei @lysign

**Comment by lysign** [comment]
Fixes #127

**Comment by moweiwei** [comment]
#close
