### ISSUE TITLE
K8S cluster online install failed

### ISSUE THREAD

**Issue by sacredartr** [kubeclipper/kubeclipper#166]
**Describe the Bug**
K8S cluster online install failed

**Versions Used**
Kubernetes: v1.23.6
Kubeclipper: master

**Environment**
How many nodes and their hardware configuration:

CentOS 7.7.1908
masters: 4cpu/8g

**How To Reproduce**
1. Go to 'Cluster Manager - Cluster'
2. Click on 'Create Cluster'
3. Fill in  config and set Online Image Type
4. install failed
5. But click 'Retry from wrong step', it success

**Screenshot**

<img width="1206" alt="企业微信截图_81188cf4-b29b-4c90-af38-6049ee1f5f38" src="https://user-images.githubusercontent.com/56632872/187173951-22bca35f-c65b-4792-aed8-a4a3848e0f9d.png">

**Comment by x893675** [comment]
/kind need-verify
@sacredartr
