### ISSUE TITLE
The PATH of the machine needs to be considered when installing with kcctl.sh

### ISSUE THREAD

**Issue by sacredartr** [kubeclipper/kubeclipper#218]
**Describe the Bug**
The PATH of the machine needs to be considered when installing with kcctl.sh

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
Kubernetes: v1.23.6
Kubeclipper: master

**Environment**
How many nodes and their hardware configuration:

CentOS 7.7 / 1 masters: 4cpu/8g

** Screenshot**

![截屏2022-09-13 16 50 30](https://user-images.githubusercontent.com/56632872/190100768-9ca58312-c813-4d65-8d9e-1adae5dde7c0.png)

**Comment by qinyer** [comment]
The script for installing `kcctl` now supports dynamically adjusting the installation directory, it will parse the current server's `PATH` environment variable to find `/usr/local/bin` or `/usr/bin` as the installation path; You can also specify a custom installation path by setting the `KC_BIN_DIR` environment variable.

So I'm going to close this issue.

/close
