### ISSUE TITLE
When iptables is selected in proxy mode, the cluster deletion fails

### ISSUE THREAD

**Issue by Mengchenchen** [kubeclipper/kubeclipper#288]
**Describe the Bug**
When iptables is selected in proxy mode, the cluster deletion fails
For UI issues please also add a screenshot that shows the issue.

<img width="1679" alt="删除" src="https://user-images.githubusercontent.com/100403985/197096987-77a99586-0e68-48ce-a991-1e68f26076a4.png">

**Versions Used**

Kubeclipper:v1.2.1

**Comment by wu-wenxiang** [comment]
https://github.com/kubeclipper/kubeclipper/pull/282
