### ISSUE TITLE
offline arg in kcctl cluster create command usage is confusing

### ISSUE THREAD

**Issue by gongysh2004** [kubeclipper/kubeclipper#579]
**Describe the Bug**
offline arg in kcctl cluster create command usage is confusing.  `-offline <online> | <offline>` should be `--offline <false> | <true>`

**Versions Used**
Kubernetes:
Kubeclipper:

```
root@compute1:~# kcctl version
kcctl version: version.Info{Major:"1", Minor:"3+", GitVersion:"v1.3.1-rc.94+6982d82e748c19", GitCommit:"6982d82e748c19422447cda3fd85128d18c08098", GitTreeState:"clean", BuildDate:"2023-05-08T08:20:35Z", GoVersion:"go1.19.8", Compiler:"gc", Platform:"linux/amd64"}
```

**How To Reproduce**
```
# kcctl create cluster -h

Usage:
  kcctl create cluster (--name) <name> (-m|--master) <id or ip> [(--offline <online> | <offline>)] [(--cri <docker> | <containerd>)] [(--cni <calico> | <others> )] [flags]
```

` `

**Expected behavior**
I think it should be：
` kcctl create cluster (--name) <name> (-m|--master) <id or ip> [(--offline <false> | <true>)] [(--cri <docker> | <containerd>)] [(--cni <calico> | <others> )] [flags]`

**Comment by jingchu000** [comment]
Hi @kubeclipper-bot , Can I work on this?

**Comment by jingchu000** [comment]
Hi @kubeclipper-bot @lixd  , Can I work on this?

**Comment by lixd** [comment]
of course,this is great,thanks.

/assign @jingchu000
