### ISSUE TITLE
kcctl join failed with unmarshaling error

### ISSUE THREAD

**Issue by likakuli** [kubeclipper/kubeclipper#597]
**Describe the Bug**

kcctl join --agent default:1.2.3.4

get online deploy-config failed: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field AuditOptions.audit.retentionPeriod of type time.Duration  

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
Kubernetes: 1.22
Kubeclipper: 1.3.1

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by likakuli** [comment]
audit:
      retentionPeriod: 168h0m0s
      maximumEntries: 200
      auditLevel: Request

**Comment by x893675** [comment]
/kind need-verify
@sacredartr

**Comment by lixd** [comment]
You can reopen the issue at any time if it still exists.
