### ISSUE TITLE
May I ask where to download the offline installation package of K8S? 

### ISSUE THREAD

**Issue by fangweisi** [kubeclipper/kubeclipper#680]
May I ask where to download the offline installation package of K8S? After deploying kubeclipper, I selected offline when creating the cluster. Only version 1.27 is available. I would like to select other versions for offline installation.

**Comment by qinyer** [comment]
Hello, please check [this document](https://kubeclipper.io/docs/getting-started/make-offline-package/)，follow the instructions in the document.
