### ISSUE TITLE
How to build special version Offline pkgs?

### ISSUE THREAD

**Issue by okeyear** [kubeclipper/kubeclipper#797]
You don't need to remove this comment section, it's invisible on the issues page.

## General remarks

* Attention, please fill out this issues form using English as much as possible!
* 注意！GitHub Issue 请尽量使用英文
- k8s https://kubernetes.io/releases/
- containerd  https://containerd.io/downloads/#releases
- calico https://github.com/projectcalico/calico/releases
- docker https://download.docker.com/linux/static/stable/x86_64/

在文档
Refer to docs: https://kubeclipper.io/docs/getting-started/make-offline-package/ 中, 发现OSS上部分离线包并没有;
Some special version packages were not found in OSS storage.
以k8s为例,  比如下载时候, 大概过程如下
For example k8s, the steps should be:
```shell
k8s_ver='v1.31.1'
# 从 oss 下载然后打成 tar.gz 包即可,命令如下
mkdir -p k8s/${k8s_ver}/amd64
pushd k8s/${k8s_ver}/amd64
# 下载准备好的离线包
wget https://oss.kubeclipper.io/packages/k8s/${k8s_ver}/amd64/manifest.json
wget https://oss.kubeclipper.io/packages/k8s/${k8s_ver}/amd64/images.tar.gz
wget https://oss.kubeclipper.io/packages/k8s/${k8s_ver}/amd64/configs.tar.gz
popd
tar -zcvf k8s-${k8s_ver}-amd64.tar.gz  k8s
# 然后使用 kcctl resource push 命令进行推送
kcctl resource push --pkg k8s-${k8s_ver}-amd64.tar.gz --type k8s
```

There are 3 files:
可以看到, 最主要的文件有三个
manifest.json
images.tar.gz
configs.tar.gz

After download k8s v1.30.6 images , and tar to images.tar.gz,  how to generate the meta file manifest.json and configs.tar.gz ?
如果想要自己拉取其他版本的资源, 比如k8s的v1.30.6并打包成images.tar.gz;
如何生成元数据文件manifest.json 和 configs.tar.gz ?

**Comment by lixd** [comment]
完整离线包分为三部分：
images.tar.gz： 镜像部分，docker save 方式保存即可
configs.tar.gz：二进制文件、shell 脚本以及一些配置文件等，对 k8s 来说则是包括 kubectl、kubeadm 等，以及 kubelet 启动的配置文件
manifest.json：主要为上述两个文件的 md5 值信息
暂时没有提供完整的打包脚本，可以先参考下已有的离线包

**Comment by lixd** [comment]
ps：oss 上更新了 1.30.6 的包
