### ISSUE TITLE
support natsio persistence

### ISSUE THREAD

**Issue by sacredartr** [kubeclipper/kubeclipper#88]
**Describe the Bug**
The cluster always in progress when terminating cluster

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
Kubernetes: v1.1.0
Kubeclipper: v1.1.0

**Environment**
How many nodes and their hardware configuration:

CentOS 7.7.1908
masters: 4cpu/8g

**How To Reproduce**

Go to 'Cluster Manager - Cluster'
Select a cluster and click on 'Delete'
Jump to 'Cluster Manager - Cluster'
The Cluster is always in progress

** Screenshot**

<img width="1406" alt="企业微信截图_32b214be-40ba-4661-b2ed-fcebdba15f4e" src="https://user-images.githubusercontent.com/56632872/183846635-66c95ac8-9c52-41a2-a747-e85ce085c7b8.png">

![企业微信截图_2c8491ff-bc92-485e-b7e2-973ebd607548](https://user-images.githubusercontent.com/56632872/183847130-fd733d71-9657-4247-8c2d-0b49050507a4.png)

**Comment by x893675** [comment]
/kind need-verify
I think it caused by poor network environment
@qinyer @sacredartr

**Comment by x893675** [comment]
maybe we can support natsio persistence to avoid lost message between server and agent
/remove-kind need-verify
/milestone v1.2.0
/kind feature

**Comment by x893675** [comment]
ref:
* https://docs.nats.io/reference/faq
* https://docs.nats.io/nats-concepts/jetstream

**Comment by x893675** [comment]
support external natsio now.
/close
